"""initial migration

Revision ID: 33236d0e459c
Revises: 
Create Date: 2026-03-02 20:32:09.277203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33236d0e459c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Company_id'), table_name='company')
    op.drop_index(op.f('ix_Company_location'), table_name='company')
    op.create_index(op.f('ix_company_id'), 'company', ['id'], unique=False)
    op.create_index(op.f('ix_company_location'), 'company', ['location'], unique=True)
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'company_id')
    op.drop_index(op.f('ix_company_location'), table_name='company')
    op.drop_index(op.f('ix_company_id'), table_name='company')
    op.create_index(op.f('ix_Company_location'), 'company', ['location'], unique=True)
    op.create_index(op.f('ix_Company_id'), 'company', ['id'], unique=False)
    # ### end Alembic commands ###
