"""remove unique constraint from location

Revision ID: 67be595420aa
Revises: 
Create Date: 2026-03-05 20:58:06.532103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67be595420aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_company_location'), table_name='company')
    op.create_index(op.f('ix_company_location'), 'company', ['location'], unique=False)
    op.create_foreign_key(None, 'users', 'company', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_company_location'), table_name='company')
    op.create_index(op.f('ix_company_location'), 'company', ['location'], unique=True)
    # ### end Alembic commands ###
